



import java.awt.Window;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class login extends javax.swing.JInternalFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogar = new javax.swing.JButton();
        tbSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tbUsuario = new javax.swing.JTextField();

        setTitle("Login");

        btLogar.setText("LOGAR");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });

        jLabel14.setText("SENHA:");

        jLabel13.setText("LOGIN:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btLogar)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        Usuario pr = null;
        String usuario;
        String senha;
        
         
//        login lo = new login();
//        
//        
//        if (!(tbUsuario.getText().equals(""))) {
//            
//            try {
//                BDusuario bd = new BDusuario();
//                pr = bd.procurarUsuario(tbUsuario.getText());
//                if (pr != null) {
//                    
//                    usuario = tbUsuario.getText();
//                    senha = tbSenha.getText();
//                    
//                    if (senha.equals(pr.getSenha()) & usuario.equals(pr.getUsuario())) {
//                        
//                        if(pr.isTrocaSenha() == true){
//                            this.dispose();
//                            JOptionPane.showMessageDialog(null, "trocar");
//                            trocarSenha ts = new trocarSenha();
//                            menu.desktop.add(ts);
//                            ts.setVisible(true);
//                            trocarSenha.lbTrocaSenhaUsuario.setText(tbUsuario.getText());
//                                                       
//                        }else{
//                        if ("326".equals(pr.getUsuario())) {
//                            menu.btCadUsuario.setVisible(true);
//                        }
//                        menu.btTela.setEnabled(true);
//                        menu.btVendas.setEnabled(true);
//                        
//                        }   
//                    } else {
//                        JOptionPane.showMessageDialog(null, "login ou senha invalidos ");
//                    }
//                    
//                } else {
//                    JOptionPane.showMessageDialog(null, "login ou senha invalidos");
//                    
//                }
//                menu.tbBemVindos.setText("Bem Vindo(a) " + pr.getNome()); 
//            } catch (SQLException ex) {
//            }
//           
//        }
//        
//        tbUsuario.setText("");
//        tbSenha.setText("");
//        menu.btLogin.setEnabled(true);
        this.dispose();

        //        tela.setVisible(true);
        //        login.setVisible(false);
        menu.btLogin.setEnabled(true);
        menu.btTela.setEnabled(true);
        menu.btCadUsuario.setEnabled(true);
        menu.btRme.setEnabled(true);
    }//GEN-LAST:event_btLogarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPasswordField tbSenha;
    private javax.swing.JTextField tbUsuario;
    // End of variables declaration//GEN-END:variables
}
